name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Test"
        run: |
          curl -s https://bashunit.typeddevs.com/install.sh | bash
          ./lib/bashunit ./tests/*_test.sh
          rm -rf ./lib
