name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Install bashunit"
        run: "curl -s https://bashunit.typeddevs.com/install.sh"

      - name: "Test"
        run: "./lib/bashunit tests/*_test.sh"
